# Specify that we want to compile all rust features ourselves for our own architecture
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# The default built target / configuration to use
[build]
target = "x86_64-fern.json"

# Use the custom boot image runner
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
